### PR TITLE
Fix error when clicking on photo preview (not circle) in android

### LINKED ISSUE #9: Error when touch on the photo selection
Hi, that is great pakage, config pakage so easy, fast. But when touch on the photo selection, it action good while i touch to circle, but when I touch outside of the circle (background) the app crashes (Android)

### PR DESCRIPTION
**Pull request by James-Firth**
Resolves #9

Tested on Samsung Galaxy S10

Solution found via this issue https://github.com/q805699513/PhotoPicker/issues/7
and the README in the main library here: https://github.com/q805699513/PhotoPicker

### CODE REVIEW

**Comment by James-Firth** [comment]
It seems the newer versions of pictureselector will fix this. 
I think it is only a release candidate so I am suggesting this fix that does not require waiting for LuckSiege to create a full release of their library.

There may be a better way to implement this fix, but I have tested this one.

https://github.com/ymane/react-native-multiple-image-picker/commit/0ebf63f9ab97a6be85e394b93eb32c4a964ad8f8

**Comment by James-Firth** [comment]
Oh great, thanks! I will close this and do some testing later then.

If the problem persists I will reply and re-open a Pull Request if necessary

**Comment by uplamartya** [comment]
I am facing this issue in IOS

**Comment by SimonImbrogno** [comment]
> Thanks for your contribution. I fixed it in the new version. Please reply to me if the problem persists

The problem still persists. The fix presented in this PR _does_ seem to resolve the issue though.

**Pull request closed without merging**
