### PR TITLE
🌈 HXPhoto Picker & Nitro Modules

### PR DESCRIPTION
**Pull request by baronha**
As mentioned in many previous issues. I will convert [TLPhotoPicker](https://github.com/tilltue/TLPhotoPicker) to [HXPhotoPicker](https://github.com/SilenceLove/HXPhotoPicker) because of the convenience and seamless commits from HXPhotoPicker.
Next I will use [Nitro Modules](https://github.com/mrousavy/nitro/) instead of Turbo Module. Turbo Module limits my ability to write Swift and Nitro's speed is superior.

I will finish it in the next few weeks. Waiting for me 😗😗😗

### CODE REVIEW

**Comment by anhquan291** [comment]
Can't wait @baronha

**Comment by baronha** [comment]
> Can't wait @baronha

No hope

**Comment by anhquan291** [comment]
Approved!

**Review by baronha — COMMENTED** [review]
Complete 2.0

**Comment by baronha** [comment]
@anhquan291 Merged =))) But not `/main`

**Pull request merged**
